HeatTemplateFormatVersion: '2012-12-12'
Description: |
  Template which creates some simple resources
Parameters:
  trigger:
    Type: String
    Default: not_yet
  image:
    Type: String
Resources:
  fluffy:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      kittens:
      - Tom
      - Stinky
    Properties:
      ImageId: {Ref: image}
      InstanceType: not_used
      UserData:
        Fn::Replace:
        - variable_a: {Ref: trigger}
          variable_b: bee
        - |
          A == variable_a
          B == variable_b
Outputs:
  fluffy:
    Description: "fluffies irc nick"
    Value:
      Fn::Replace:
      - nick: {Ref: fluffy}
      - |
        #nick
