#!/bin/sh

set -e

cd /var/lib/tempest

if [ ! -d .testrepository ] ; then
	testr init
fi

testr run --parallel --subunit $@ | subunit-2to1 | python /usr/lib/python2.7/dist-packages/tempest/colorizer.py
